name: Lint

on:
  pull_request:
    branches: [ "master", "develop" ]

  workflow_dispatch:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Delete nodesModules
        run: rm -rf node_modules

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Code Linting
        run: npm run lintWork
